### ISSUE TITLE
I can't find the prompt for "resource " in StackExchange

### ISSUE THREAD

**Issue by ppsmk388** [yueyu1030/AttrPrompt#1]
![image](https://github.com/yueyu1030/AttrPrompt/assets/60417397/70970856-a690-497c-a341-b18a2ba08cd3)
from code in gpt_gen_attrprompt.py We didn't find that stackexchange has a property called resource

But in the dataset we can find this property

![image](https://github.com/yueyu1030/AttrPrompt/assets/60417397/d5b56f95-decb-43f3-abc6-7051ec5462f6)

**Comment by ppsmk388** [comment]
A similar situation appears on the amazon dataset, prompt template with ["length", "brands", "product_name", "experience", "similar", 'style'] properties:

![image](https://github.com/yueyu1030/AttrPrompt/assets/60417397/893fe126-2870-4c97-b36f-4d6bc1d1b397)
![image](https://github.com/yueyu1030/AttrPrompt/assets/60417397/130367b0-df8d-4d01-a1c3-87c9d9621774)

But we can't find the attribute experience in the dataset, and the attribute similar isn't used in prompt:

![image](https://github.com/yueyu1030/AttrPrompt/assets/60417397/7ef982c1-d9da-4d0a-9095-cf9bbef8ad7f)

**Comment by ppsmk388** [comment]
Thank you very much for your excellent work. I hope you can help me solve this problem

**Comment by yueyu1030** [comment]
Hi there,

Thanks for your interest! For your first question, I think the dataset you mentioned is `stackexchange` instead of `reddit`. After checking the code, we found that we actually did not use this property (resource) and have removed it to avoid misunderstandings. For your second question, we have added the attributes for `experience`/`similar`. Please see
https://github.com/yueyu1030/AttrPrompt/blob/main/gen_train_data/gpt_gen_attrprompt.py#L173-L181 and https://github.com/yueyu1030/AttrPrompt/blob/main/gen_train_data/gpt_gen_attrprompt.py#L221-L227 for details. 
Hope these explanations & updates will be helpful.

Best,
Yue

**Comment by ppsmk388** [comment]
Thank you so much for your reply!
