### ISSUE TITLE
Openai api is stuck

### ISSUE THREAD

**Issue by hengfei-wang** [yueyu1030/AttrPrompt#5]
Hi,

Thank you for sharing the code. 

I tried you code with my api key. But the call of api is often stuck and no error output. Sometimes after 10 iters, somtimes after 100 iters. I am not using your prompt and design my prompt by myself. But I would think it should be same. Any ideas?

Thanks.

**Comment by yueyu1030** [comment]
Hi there,

Thank you for your interest. We have encountered this issue on occasion as well. It may be caused by the `openai.error.APIError`, possibly stemming from the high volume of API queries from the server. To alleviate this, we recommend you try on the script in [this link](https://github.com/openai/openai-cookbook/blob/main/examples/api_request_parallel_processor.py), which might be more efficient.

Best,
Yue

**Comment by hengfei-wang** [comment]
Hi,

Thank you for your reply. I found my problem is caused by openai.error.timeout. So I just set request_timeout=10 in the function. Problem solved. 

Thanks.
